name: CI
on:
  workflow_dispatch:

    inputs:
     Env:
        type: choice
        options:
          - QA
          - Staging
          - Production
     browser:
      description: "Browser type"
      required: true
      default: "Edge Chromium"
      type: choice
      options:
          - chrome
          - firefox
          - Edge Chromium
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2.1
      with:
          version: '10.4.2'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -browserType="${{ github.event.inputs.Browser }}" -statusDelay=15 -testSuitePath="Test Suites/Appointment" -apiKey="1dcc123f-13e5-4d69-a0a3-84447f54498f" --config -webui.autoUpdateDrivers=true'
